# Numpy array

In [1]:
import numpy as np


In [9]:
Distance=[230,340,550,770]
Time=[40,50,60,70]
dist=np.array([Distance])
time=np.array([Time])
type(dist)
speed=dist/time
print(speed)

[[ 5.75        6.8         9.16666667 11.        ]]


In [8]:
import numpy as np
a="my name is mr khan"
b=np.array(a)
b

array('my name is mr khan', dtype='<U18')

In [12]:
type(b)

numpy.ndarray

In [17]:
b.dtype

dtype('<U18')

In [10]:
c=np.array([1,2,3,4])


In [11]:
c.astype(float)


array([1., 2., 3., 4.])

In [32]:
type(c)

numpy.ndarray

In [15]:
c.dtype

dtype('float64')

In [12]:
print(c)

[1 2 3 4]


In [14]:
d=np.array([1,2.4,'cetpa'])
d

array(['1', '2.4', 'cetpa'], dtype='<U32')

In [20]:
d.dtype

dtype('<U32')

In [22]:
d.ndim

1

In [15]:
z=np.array([[1,2,3,4],[5,6,7,8,]])
z

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
z.ndim

2

In [17]:
z.shape

(2, 4)

In [18]:
z.size

8

In [29]:
#size=product of elements in->output of shape 

In [30]:
z.dtype

dtype('int32')

In [1]:
#build-in numpy array
# arange->return evenly spaced value with in a given interval

In [2]:
import numpy as np

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#Linspace->return evenly spaced numbers over a specified interval

In [14]:
import numpy as np

In [26]:
np.linspace(0,10,2)

array([ 0., 10.])

In [28]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [29]:
np.linspace(0,20,50)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [20]:
#eye->create an identity matrix

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
#Random ->numpy also had lots of way to create random number arrays

In [24]:
#Rand->create an array of an given shape and populate it with random sample from a uniform distribution over [0,1] 

In [34]:
np.random.rand(3,4)

array([[0.85945041, 0.26371331, 0.41813921, 0.34625648],
       [0.08930956, 0.67595701, 0.34020413, 0.98596371],
       [0.87863542, 0.33802354, 0.63432354, 0.47743003]])

In [26]:
np.random.rand(5,5)

array([[0.30685151, 0.71969959, 0.97174152, 0.3599261 , 0.40661408],
       [0.75118349, 0.96618693, 0.15923881, 0.24427198, 0.05615616],
       [0.49028773, 0.47786959, 0.55409127, 0.36856229, 0.10729225],
       [0.51502569, 0.36463347, 0.27563118, 0.61152827, 0.25255747],
       [0.05231244, 0.50480799, 0.04113939, 0.1014773 , 0.07712354]])

In [27]:
np.random.rand(50,50)

array([[0.19193866, 0.71659669, 0.12795051, ..., 0.73980971, 0.23301885,
        0.16716361],
       [0.15391272, 0.17298618, 0.3609944 , ..., 0.04089078, 0.21304725,
        0.70957221],
       [0.0948281 , 0.79950529, 0.95745976, ..., 0.09641879, 0.11837131,
        0.47949259],
       ...,
       [0.47196486, 0.61025691, 0.70111944, ..., 0.90420798, 0.96841434,
        0.45070256],
       [0.5765026 , 0.96120678, 0.48459522, ..., 0.36209411, 0.851501  ,
        0.84752421],
       [0.89707155, 0.87743666, 0.89648232, ..., 0.83668523, 0.78907271,
        0.67764864]])

In [1]:
#Randn->return a sample(or samples)from the "standard normal

In [2]:
#randint->

In [3]:
#Bracket indexing and Selection_---->the simplest way to pick one or some elements of an array looks very simple to  python lists

In [35]:
import numpy as np

In [37]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[4]

4

In [19]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
a=np.arange(50,200,2)
a

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100,
       102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
       128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152,
       154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178,
       180, 182, 184, 186, 188, 190, 192, 194, 196, 198])

In [48]:
ab=a+arr

ValueError: operands could not be broadcast together with shapes (75,) (11,) 

In [25]:
##when ever we have to perform any mathematical oprtation on two numpy array  are two condition 
#1.they both should have equal no of elements
#2.either any one of them will contain only single elemesnts

In [53]:
A=np.array([5])

In [54]:
B=np.array([1,2,3,4,5])

In [55]:
A+B

array([ 6,  7,  8,  9, 10])

In [56]:
B[0:4]=50

In [57]:
B

array([50, 50, 50, 50,  5])

In [33]:
#Broadcast-->numpy array differ 


In [34]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

In [35]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [74]:
#reset array, we will see why i had to reset in a moment
import numpy as np
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
#import notes on slices
slices_of_arr = arr[0:6]

#show Slices
slices_of_arr

array([0, 1, 2, 3, 4, 5])

In [76]:
#change slices
slices_of_arr[:]=99

#Show slices again
slices_of_arr

array([99, 99, 99, 99, 99, 99])

now the changes is also occur in our original array

In [77]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied. its a view of the original array! This avoid memory problems 

In [41]:
#To get a copy ,need to be explict
arr_copy=arr.copy()

In [42]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [43]:
Ab=ab.array([1,2,3,4,])
Ba=ab.array([5,6,7,8,])

In [45]:
z=ab.array([[1,2,3,4,],[5,6,7,8,]])

In [78]:
z[0]

array([1, 2, 3, 4])

In [79]:
z[1]

array([5, 6, 7, 8])

In [81]:
z[:,1]

array([2, 6])

In [51]:
z[:,1:3]

array([[2, 3],
       [6, 7]])

In [83]:
z[:,:1]

array([[1],
       [5]])

In [84]:
import numpy as numpy


In [85]:
my_array = numpy.array([[1,2],[3,4]])

In [86]:
print(numpy.mean(my_array,axis =0))
print(numpy.mean(my_array,axis =1))
print(numpy.mean(my_array,axis =None))
print(numpy.mean(my_array))

[2. 3.]
[1.5 3.5]
2.5
2.5


In [67]:
my_array.max()

4

In [68]:
my_array.min()

1

# Mean vs Median

lets create  some fake income data centered around 27000 with a normal distribution and standerd daviation discus those terms those terms more latter if you are not familiar with them
then compute the mean (average) it should be close to 27000:

In [98]:
import numpy as np
incomes = np.random.normal(15000,20000,10000)
print(incomes)
np.mean(incomes)

[ 32642.19372783  58466.48266274  37744.79445793 ... -18227.76690781
  38897.09882611  44138.32407974]


14881.847748766582

In [2]:
incomes = np.append(incomes,10000000)

In [3]:
print(incomes)
np.mean(incomes)

[   38945.7027643     35594.67250547    31071.95435859 ...
    27671.04333844    45989.40159039 10000000.        ]


28024.841624470617

we never replace non values with the mean if we have some outliers present in the data 
ex-> in the avobe income data sets the mean of incomes of 10000 peoples is 27000 but just by adding a one outlier i.e 
Donald trump income effect the mean value very much

In [106]:
import numpy as np
ages= np.random.randint(18, high=90, size=500)
print(ages)
ages.size

[84 19 80 89 61 56 22 28 54 76 64 19 85 85 51 28 55 38 36 61 22 36 63 87
 28 86 29 55 85 35 76 63 57 47 45 26 64 48 44 84 88 38 85 64 31 64 25 35
 85 63 47 42 63 36 19 32 88 41 49 87 77 49 41 66 19 25 30 78 33 23 18 77
 73 28 88 81 82 59 31 86 49 66 49 70 76 19 86 67 24 77 39 41 19 39 51 41
 25 65 67 86 51 30 82 41 89 89 87 71 57 18 27 65 40 74 46 56 47 45 70 68
 36 34 62 88 25 43 34 74 25 87 34 77 75 72 81 84 18 39 58 41 58 66 84 75
 74 60 87 25 69 86 50 61 57 74 18 34 30 81 67 62 32 83 19 23 25 56 74 21
 47 59 36 43 38 85 32 79 58 37 19 36 56 22 69 34 65 52 24 71 66 86 30 63
 36 80 22 31 56 26 75 71 64 86 20 81 60 73 20 34 86 59 22 29 74 60 21 89
 40 18 71 67 88 19 31 64 74 42 71 77 30 53 27 28 57 43 21 53 31 48 44 43
 40 29 45 52 51 85 33 69 58 29 72 80 75 29 19 19 62 23 45 60 36 88 31 55
 76 66 73 67 67 47 28 63 50 52 83 60 60 40 86 86 27 42 76 67 68 68 33 73
 82 42 26 69 37 85 28 44 33 48 88 79 27 55 42 44 38 83 83 60 33 79 58 18
 61 65 32 58 26 40 23 63 62 77 30 42 77 78 44 73 36

500

In [6]:
from scipy import stats
stats.mode(ages)

ModeResult(mode=array([79]), count=array([14]))

In [7]:
import numpy as np

In [112]:
a = np.array([[2,0],[3,0],[3,1],[8,0],[5,1],[5,2]]).reshape(2,6)
a

array([[2, 0, 3, 0, 3, 1],
       [8, 0, 5, 1, 5, 2]])

In [113]:
np.max(a)
a.ndim
a.shape

(2, 6)

In [41]:
i,j=np.where(a==np.max(a))
i,j

(array([3], dtype=int64), array([0], dtype=int64))

# standerd daviation and variance

In [46]:
incomes.std()

100845.09496519473

In [45]:
#variance
incomes.var()

10169733178.539143

In [1]:
import numpy as np


# Question no 5 

create a  (5,5) matrix with random no & find the max and min values

In [119]:
a=np.random.rand(5,5)
a

array([[0.35042602, 0.24720716, 0.53431537, 0.34140504, 0.77526218],
       [0.11359695, 0.95356919, 0.46102348, 0.38156102, 0.87094823],
       [0.86212023, 0.08176239, 0.64460217, 0.3681438 , 0.62747774],
       [0.45376353, 0.69071807, 0.19339116, 0.33526378, 0.25348481],
       [0.79573013, 0.01593932, 0.22674688, 0.79522851, 0.74037829]])

In [117]:
print(np.min(a))
print(np.max(a))

0.034974588884033375
0.9945889276176574


Question no 1:-> create an null vector of size 10 and update sixth value to 11 

In [11]:
import numpy as np
a=np.zeros(10)
a


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
a[6]=11

In [13]:
a

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

In [14]:
a[8]=77

In [15]:
a

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0., 77.,  0.])

In [17]:
import numpy as np


Question 2 convert int array into float

In [43]:
import numpy as np

In [44]:
arr=np.array([1,2,3,4])

In [45]:
print(arr.astype(float))

[1. 2. 3. 4.]
